SELECT 
   CD_PESSOA_FISICA,
   NR_ATENDIMENTO,
   CD_MEDICO,
   TASY.OBTER_DESC_SETOR_ATEND(CD_SETOR_ATENDIMENTO) SETOR,
   DT_LIBERACAO,
   TASY.OBTER_NOME_ESTABELECIMENTO(99) ESTABELECIMENTO,
   TASY.OBTER_NOME_PF(CD_PESSOA_FISICA) NOME,
   TASY.OBTER_NOME_CONVENIO(CD_CONVENIO) CONVENIO,
   TASY.OBTER_CATEGORIA_CONVENIO(CD_CONVENIO, CD_CATEGORIA) CATEGORIA
FROM (
    SELECT
        AP.CD_PESSOA_FISICA,
        AP.NR_ATENDIMENTO,
        PM.CD_MEDICO,
        (SELECT MAX(PIS.CD_SETOR_ATENDIMENTO)
        FROM TASY.PROC_INTERNO_SETOR PIS
        WHERE 1 = 1
            AND PIS.CD_ESTABELECIMENTO = PII.CD_ESTABELECIMENTO
            AND PIS.NR_SEQ_PROC_INTERNO = PII.NR_SEQ_PROC_INTERNO
        ) CD_SETOR_ATENDIMENTO,
        PM.DT_LIBERACAO,
        CASE
           WHEN ACC.CD_CONVENIO IN (1, 7, 30, 26, 9) AND TPM.DS_MODALIDADE IN ('CR','US') THEN 582
           WHEN ACC.CD_CONVENIO IN (270, 13) AND TPM.DS_MODALIDADE IN ('CR','CT','US') THEN 582
           WHEN ACC.CD_CONVENIO = 254 AND TPM.DS_MODALIDADE = 'CR' THEN 582
           WHEN ACC.CD_CONVENIO IN (21, 516, 305, 29, 49, 33, 82, 754, 60) THEN 582
           ELSE TO_NUMBER(ACC.CD_CONVENIO)
        END AS CD_CONVENIO,
        CASE
           WHEN ACC.CD_CONVENIO = 270 AND TPM.DS_MODALIDADE IN ('CR','CT','US') THEN 10
           WHEN ACC.CD_CONVENIO = 13 AND TPM.DS_MODALIDADE IN ('CR','CT','US') THEN 24
           WHEN ACC.CD_CONVENIO IN (1, 7) AND TPM.DS_MODALIDADE IN ('CR','US') THEN 1
           WHEN ACC.CD_CONVENIO = 9   AND TPM.DS_MODALIDADE IN ('CR','US') THEN 21
           WHEN ACC.CD_CONVENIO = 30  AND TPM.DS_MODALIDADE IN ('CR','US') THEN 2
           WHEN ACC.CD_CONVENIO = 26  AND TPM.DS_MODALIDADE IN ('CR','US') THEN 3
           WHEN ACC.CD_CONVENIO = 254 AND TPM.DS_MODALIDADE = 'CR' THEN 17
           WHEN ACC.CD_CONVENIO = 21  THEN 5
           WHEN ACC.CD_CONVENIO = 516 THEN 7
           WHEN ACC.CD_CONVENIO = 305 THEN 14
           WHEN ACC.CD_CONVENIO = 29  THEN 15
           WHEN ACC.CD_CONVENIO = 49  THEN 16
           WHEN ACC.CD_CONVENIO = 33  THEN 18
           WHEN ACC.CD_CONVENIO = 82  THEN 19
           WHEN ACC.CD_CONVENIO = 754 THEN 20
           WHEN ACC.CD_CONVENIO = 60  THEN 22
           ELSE TO_NUMBER(ACC.CD_CATEGORIA)
        END AS CD_CATEGORIA,
        ROW_NUMBER() OVER (PARTITION BY AP.CD_PESSOA_FISICA ORDER BY AP.NR_ATENDIMENTO DESC) AS RN
    FROM TASY.ATENDIMENTO_PACIENTE AP
    JOIN TASY.ATEND_PACIENTE_UNIDADE APU    ON APU.NR_ATENDIMENTO = AP.NR_ATENDIMENTO
    JOIN TASY.ATEND_CATEGORIA_CONVENIO ACC  ON ACC.NR_ATENDIMENTO = AP.NR_ATENDIMENTO
    JOIN TASY.PRESCR_MEDICA PM              ON PM.NR_ATENDIMENTO = AP.NR_ATENDIMENTO
    JOIN TASY.PRESCR_PROCEDIMENTO PP        ON PP.NR_PRESCRICAO = PM.NR_PRESCRICAO
    JOIN TASY.PROCEDIMENTO P                ON P.CD_PROCEDIMENTO = PP.CD_PROCEDIMENTO
    JOIN TASY.TIPO_PROCED_MODALIDADE TPM    ON TPM.CD_TIPO_PROCEDIMENTO = P.CD_TIPO_PROCEDIMENTO
    JOIN TASY.PROC_INTERNO_INTEGRACAO PII   ON PII.NR_SEQ_PROC_INTERNO = PP.NR_SEQ_PROC_INTERNO AND  PII.CD_ESTABELECIMENTO = 99 -- UMC Imagem LTDA
    WHERE 1 = 1
        AND AP.CD_ESTABELECIMENTO = 101 -- Uberlândia Medical Center
        AND PM.CD_UNID_BASICA = 'PA'
        AND PM.DT_LIBERACAO >= TRUNC(SYSDATE)  --TO_DATE(:DATAINICIO, 'DD/MM/YYYY HH24:MI:SS')
--        AND TRUNC(PM.DT_LIBERACAO) BETWEEN TO_DATE(:DATAINICIO, 'DD/MM/YYYY HH24:MI:SS') AND TO_DATE(:DATAFIM, 'DD/MM/YYYY HH24:MI:SS')
--        AND TRUNC(PM.DT_LIBERACAO) >= TO_DATE('04/09/2025 00:00:00', 'DD/MM/YYYY HH24:MI:SS')
) A
WHERE RN = 1
    AND CD_SETOR_ATENDIMENTO IS NOT NULL
    AND NOT EXISTS(
        SELECT 1
        FROM TASY.ATENDIMENTO_PACIENTE AP
        WHERE AP.CD_ESTABELECIMENTO = 99 -- UMC Imagem LTDA
            --AND TRUNC(AP.DT_ATUALIZACAO) >= TRUNC(SYSDATE)
            AND AP.DS_OBSERVACAO LIKE '%' || A.NR_ATENDIMENTO || '%'
    )

    --AND CD_PESSOA_FISICA in (1947473)

ORDER BY DT_LIBERACAO ASC
